[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
