[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
